Guides folder and README.md
retro-dev-rblx/Docs pull request #1
Opened 2023-07-01 01:04 UTC by trademark-living-his-best-life

Guides page for coding tutorials

2023-07-01 01:55 UTC, FloofyPlasma commented
Hello, thank you for your pull request. I will now be reviewing your contributions. I will let you know if there are any changes required.

2023-07-01 02:27 UTC, FloofyPlasma requested changes
I have left comments on areas you should change.

2023-07-01 02:27 UTC, FloofyPlasma commented on code-blocks/miscellaneous/run/for-loop.md
> +description: Clones an object.
Make sure you update the description too.

2023-07-01 02:41 UTC, FloofyPlasma commented
I am going to convert your PR to a draft, once its done you may change it back.

2023-07-01 05:13 UTC, trademark-living-his-best-life commented
> Hello, thank you for your pull request. I will now be reviewing your contributions. I will let you know if there are any changes required.

alright, still gonna work on stuff tommorow

2023-07-01 05:17 UTC, trademark-living-his-best-life commented on guides/simple/for-loops.md
> +This will not only cover the For Loop block, also but the Loop Through Table, Loop Through Children, and Loop Through Decendants.
Changed the entire page to just be about Loops.

2023-07-08 23:34 UTC, FloofyPlasma approved these changes

2023-07-08 23:34 UTC, merged