Patch 5
retro-dev-rblx/Docs pull request #31
Opened 2023-07-26 22:07 UTC by randompea

# Pull Request Title Here

My pull request is to
- [x] Add documentation
- [ ] Fix documentation

If adding documenation, I am adding it to
- [x] Code blocks
- [ ] Objects
- [ ] Guides

If adding documentation, did I
- [x] Correctly format the page to match the other ones
- [x] Add it to the index page for the correct category
- [x] Add it to SUMMARY.md

# Additional information

I added some miscellaneous - miscellaneous stuff.

Whoever did the saving part - i saved you, you forgot to add it to code block index so it didn't show up there. (pun intended) (saving part is save variable save instance that one)

2023-07-30 21:48 UTC, FloofyPlasma requested changes

2023-07-30 21:48 UTC, FloofyPlasma commented on code-blocks/miscellaneous/miscellaneous/reload-place.md
> +# Loop Through Children
Please fix

2023-07-31 02:18 UTC, randompea commented on code-blocks/miscellaneous/miscellaneous/reload-place.md
> +# Loop Through Children
Done.

2023-07-31 19:46 UTC, FloofyPlasma approved these changes
Thank you!

2023-07-31 19:46 UTC, merged